name: build-android
on: [push, pull_request]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install MAUI workload
        run: dotnet workload install maui
      - name: Restore
        run: dotnet restore
      - name: Build Android
        run: dotnet build -c Release -f net8.0-android
