name: build-windows
on: [push, pull_request]
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install MAUI workload
        run: dotnet workload install maui
      - name: Restore
        run: dotnet restore
      - name: Build Windows
        run: dotnet build -c Release -f net8.0-windows
