name: release-drafter
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, edited]
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
